### ISSUE TITLE
Vignettes -- proposal

### ISSUE THREAD

**Issue by BERENZ** [ncn-foreigners/singleRcapture#39]
I propose the following vignettes:

1. Models -- describing distributions and models
2. Estimation of the population size -- a document that describes how the pop size and its variance is estimated 
3. Diagnostics -- post-hoc diagnostics (i.e. LOO and others)
4. Computation -- document covering estimation procedure (theory + parameters)
6. Examples -- reproducing results from selected papers and some tutorials
7. Comparison with other R packages 
8. Literature

**Comment by Kertoo** [comment]
1. is already done in help file that can be accessed from references https://ncn-foreigners.github.io/singleRcapture/reference/singleRmodels.html
2. is similarly already done in https://ncn-foreigners.github.io/singleRcapture/reference/estimatePopsize.html
4. is done in https://ncn-foreigners.github.io/singleRcapture/reference/estimatePopsize.html and https://ncn-foreigners.github.io/singleRcapture/reference/estimatePopsize.fit.html
5. is done as most help files have examples
7. is done as https://ncn-foreigners.github.io/singleRcapture/reference/estimatePopsize.html has extensive citations
6. has some work done with comparing `singleRcapture` with `VGAM`
3. is unnecessary since all diagnostics are just from `stats::glm` and `VGAM::vglm` and `sandiwch::vcovHC` etc. The only one unique to `singleRcapture` is `dfpopsize` which already has a help file (which admittedly can be more specific)

**Comment by Kertoo** [comment]
I think it would be more usefull to just add get started page on [ncn-foreigners.github.io/singleRcapture](https://ncn-foreigners.github.io/singleRcapture/) with some basic tutorial similar to e.g https://pkgdown.r-lib.org/articles/pkgdown.html

**Comment by Kertoo** [comment]
Okay that makes sense so can you manage reproduction of results from existing papers with maybe some examples of how we can use additional features in `singleRcapture` to use more accurate model/test whether model is correct i.e. no one inflation by e.g. `lmtest::lrtest`  or adding formula for `omega`/`alpha` parameters and comparisons with `countreg` and `VGAM`. I'll handle models with their interpretation and some note on computational quirks of package functions with maybe some updated tutorial.
